### ISSUE TITLE
1-regex: double precision

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#11]
Quick question: do we apply the double precision of 3 fractional digits for each input, or after computing the output?

Therefore, does 0.3996-0.3994 return:
. 0.3996-0.3994 = 0.400-0.399 = 0.001
. 0.3996-0.3994 = 0.0002 = 0

(I assume it should be 0, but just to confirm)

**Comment by tobhil98** [comment]
The specification says that the _output_ should have exactly three fractional digits. You may therefore assume that 0.3996-0.3994 = 0
