### ISSUE TITLE
1-Regex: ASCII definition

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#13]
Just to confirm, is ASCII defined as the chars between 0 and 127 or 0 and 255 (or else)?

**Comment by ymherklotz** [comment]
I believe that Flex will handle the whole 8bit range, but the spec only requires the standard 7bit ASCII range.

**Comment by JaafarRammal** [comment]
Thanks. Can I also confirm then that anything outside the 7bit range should not be tokenized as an ASCII character and therefore be rejected from the [ASCII*] rule? (Unless it will just not be tested)

**Comment by tobhil98** [comment]
It is undefined, so you can handle it however you like

**Comment by JaafarRammal** [comment]
@ymherklotz @tobhil98 this raises an issue for some of us (with @jrpdotjpg) when comparing our regex code as we have different results on random HTML pages.

In [test 20](https://github.com/LangProc/langproc-2019-lab/blob/master/1-regexes/test/in/20.txt) as it asks us to catch £ inside the [] while its ASCII code is 156 outside the range. Could we just have a clear confirmation about this ASCII issue and how it will be tested?

**Comment by tobhil98** [comment]
Basically ASCII values above 127 will not be in any of the assessed tests. You can ignore test 20 as it is ambiguous

**Comment by ymherklotz** [comment]
@JaafarRammal @jrpdotjpg 

Just a thought, with random HTML pages you might get different results if they use any UTF-8 characters, as that gets even more complicated. I believe that most HTML pages will assume UTF-8 support. 

With ASCII, I don't think that the regexes will make a difference, even if it is out of range, but I don't think flex can handle UTF-8 so you shouldn't have to worry about any differences.
