### ISSUE TITLE
Control characters in input stream

### ISSUE THREAD

**Issue by jrrrp** [LangProc/langproc-2019-lab#14]
When typing input to the lexer, you can type particular modifier characters for instance pressing the 'up' arrow, or other characters like carriage return. These break the formatting of printed output (ie it doesn't look like Word [] : 2 but instead it might span two seperate output lines). Should we try and control for this or are such characters included in the 'not spanning a line break' part of the spec? For instance backspace, up arrow, delete etc.

**Comment by tobhil98** [comment]
You do not need to treat the control characters in any other way than what is defined by the specification
