### ISSUE TITLE
Semantics of Unary Minus

### ISSUE THREAD

**Issue by Saginsky** [LangProc/langproc-2019-lab#15]
Hello, I was wondering if my understanding of the difference between a unary minus and binary minus is correct. I understand that a '-' sign is to be parsed as a unary minus if and only if it is at the beginning of an expression (i.e. an EXPR) otherwise it is a binary minus. Also, I wanted to make sure that unary minus takes precedence over +, (binary) -, *, / and has lower precedence than ^, sqrt, exp and log.

Thanks in Advance

**Comment by tobhil98** [comment]
Your understanding of the precedence seems correct.
A unary minus would not only be in front of an expression though. This would mean for example that -5+2 will be treated as -(5+2)

**Comment by Saginsky** [comment]
Ah, I see. I mean to say that the - sign will only be interpreted as a unary minus if no character precedes it unless that character is a left bracket. so in 5 + (-4*5), we'll bind the minus tighter than the multiplication but in 5 - 4*5 we would multiply first as the '-' is interpreted as binary minus since there is a character before it that isn't a left bracket. I'm not sure if that definition of unary minus is all-inclusive.

**Comment by Saginsky** [comment]
It seems the formatting removed the asterisks. The first expression was supposed to be 5+ (-4 [asterisk] 5) and the second was 5- 4 [asterisk] 5.

**Comment by tobhil98** [comment]
If the '-' was interpreted as a unary in the expression 5-4, you would have a Factor followed by a Unary. Unless you define a rule for this in your yacc file, this would not parse. The expression will instead match the case Factor followed by a Minus followed by Factor

**Comment by Saginsky** [comment]
Thanks!

**Comment by JaafarRammal** [comment]
Following over "a unary has lower precedence than ^, sqrt, exp and log", is it possible to give an example case for sort / exp / log?

**Comment by tobhil98** [comment]
I am not too sure what you are unsure about. You should be able to parse -exp(5) and exp(-5)

**Comment by JaafarRammal** [comment]
I don't see any effect of precedence change between the unary and the sqrt / exp / log

**Comment by tobhil98** [comment]
There isn't any as you put everything inside brackets

**Comment by ymherklotz** [comment]
There isn't any precedence with function calls, as the expression it acts upon has to be in the brackets.
