### ISSUE TITLE
2-parsers: OS X old bison update

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#3]
This is a personal advice for OS X users to avoid a compilation error in the lab 2.

For most devices, flex and bison are already installed using old versions. Nevertheless the lab files use a newer version of bison (such as the %code directive) which is unsupported by the older versions.

The common suggested way by the shell is to update using brew, which is blocked by the OS for security reasons. A fast way to get around this issue is to install [MacPorts](https://www.macports.org/) then install bison again using:

```
sudo port install bison
```

OS X allows MacPorts to install bash packages. The new bison will override the older version

**Comment by johnwickerson** [comment]
Very kind of you, Jaafar!
