### ISSUE TITLE
Issue running the testbenches on Lab2 on Mac?

### ISSUE THREAD

**Issue by woonmoon** [LangProc/langproc-2019-lab#6]
Did anyone else have this problem?

**Comment by JaafarRammal** [comment]
It is possible the GNU is not properly installed on the OS. One trick around it that might work is to replace a line in the test_parser.sh when defining the DOS2UNIX.

Old line:
```
DOSUNIX=“sed -e s/\x0D//g -“
```

Replace with:
```
DOSUNIX=“sed -e s/\r$//“
```

The provided test_parser.sh should run normally on Ubuntu though without this change

**Comment by woonmoon** [comment]
Thank you! It works now!

**Comment by JaafarRammal** [comment]
Correction: this concerns the dos2unix that should be in _/usr/local/bin/dos2unix_, not the GNU
