### ISSUE TITLE
3-codegen: nested_sequence test

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#7]
I was wondering if in the [nested_sequence](https://github.com/LangProc/langproc-2019-lab/blob/master/3-codegen/test/programs/nested_sequence/in.code.txt#L8) test, is the line 8 missing a _[_ or we are supposed to catch the construct syntax error with the interpreter?

Original lines:
```

1. Seq [
2.   Seq [ 
3.     Assign : x [ 10 ]
4.     Assign : y [ 11 ]
5.     Assign : z [ 10 ]
6.   ]
7.   Seq [ 
8.      Seq
9.         Assign : x [ Add [ x y ] ]
10.        Assign : z [ Add [ x z ] ]
11.     ]
12.     Output [ z ]
13.   ]
14. ]

```

**Comment by johnwickerson** [comment]
Thanks Jaafar. That's an error in the test. Fixed now; see https://github.com/LangProc/langproc-2019-lab/commit/993b1093b4afc68f94fa94483d30883867b5861b.

**Comment by JaafarRammal** [comment]
Thank you!
