### ISSUE TITLE
Flex Rule containing a period (".") and the specification of the regex lab

### ISSUE THREAD

**Issue by kimongrigorakis** [LangProc/langproc-2019-lab#8]
Within the specification of the regex lab you mention the following: "A word can also be any sequence of ASCII characters beginning with [, and ending at the next ]. The word itself does not include the surrounding [ and ] characters. You can assume that such a sequence will never span a line-break.".

A flex rule containing a period (".") will accept "any character except a newline", which seems compatible with the word specification.

However, the ASCII table contains a set of control characters like ESC (for escape) or DEL (for delete). Assuming, that the flex rule should not accept these control characters should we explicitly exclude them in the rule or are they implicitly excluded by the period (".") operator?

**Comment by tobhil98** [comment]
The flex rule containing a period will accept the control characters. However, the specification states that a word surrounded by square brackets can be _any_ sequence of ASCII characters and that you can assume that a word will _not_ contain a newline
