### ISSUE TITLE
3-codegen: redefinition of zero register

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#9]
As I might be wrong, I was wondering if the following creation of the zero register in the [ast_compile.cpp](https://github.com/LangProc/langproc-2019-lab/blob/master/3-codegen/src/ast_compile.cpp#L24) could be made in the initialization scope and use the same zero register when treating constants rather than reproducing a new zero_i register every time we are treating a constant (because we are calling makeName at every down recursion)

Scope in question:

```
if( regex_match( program->type, reNum ) ){
     std::cout<<"const "<<destReg<<" "<<program->type<<std::endl;        
}else if( regex_match( program->type, reId ) ){
     std::string zero = makeName("zero");
     std::cout<<"const "<<zero<<" 0"<<std::endl;
     std::cout<<"add "<<destReg<<" "<<program->type<<" "<<zero<<std::endl;
}
```

**Comment by ymherklotz** [comment]
Yes, as the zero register will never change value, you could assign a constant zero register and either pass it through the recursive calls or have a global variable or function that returns the name of the zero register. You just have to make sure to set that zero register is actually set to zero at the start.

I don't see any reason why that wouldn't work, it would just make your assembly shorter, but it should still behave in the same way. That would also be more similar to MIPS compilation, as it also has a hardwired 0 register in `$0`.

I'm guessing the reason it is this way is that it introduces the use of `makeName` and achieves the same result, except for more zero registers.

**Comment by JaafarRammal** [comment]
Yes indeed the goal was to make the assembly shorter for ease of debugging. Thank you for clearing out the issue!
